Update yml

diff --git a/.github/workflows/artifacts.yml b/.github/workflows/artifacts.yml
--- a/.github/workflows/artifacts.yml
+++ b/.github/workflows/artifacts.yml
@@ -31,26 +31,26 @@ jobs:
       - name: List AFTER
         run: ls -la
 
-      - name: Check if .xcodeproj exists
-        run: |
-                ls -la
-                 if [ -f "github-actions.xcodeproj" ]; then
-                 echo ".xcodeproj exists"
-                 else
-                  echo ".xcodeproj not found"
-                 exit 1
-                    fi
+      # - name: Check if .xcodeproj exists
+      #   run: |
+      #           ls -la
+      #            if [ -f "github-actions.xcodeproj" ]; then
+      #            echo ".xcodeproj exists"
+      #            else
+      #             echo ".xcodeproj not found"
+      #            exit 1
+      #               fi
 
 
-      - name: Check if .xcworkspace exists
-        run: |
-         ls -la
-             if [ -f "github-actions/github-actions.xcworkspace" ]; then
-                echo "Workspace exists"
-                else
-                 echo "Workspace not found"
-                exit 1
-             fi
+      # - name: Check if .xcworkspace exists
+      #   run: |
+      #    ls -la
+      #        if [ -f "github-actions/github-actions.xcworkspace" ]; then
+      #           echo "Workspace exists"
+      #           else
+      #            echo "Workspace not found"
+      #           exit 1
+      #        fi
 
       - name: Set up Xcode 14.3.1
         uses: maxim-lobanov/setup-xcode@v1
@@ -59,7 +59,8 @@ jobs:
 
       - name: Run Unit Tests
         run: |
-          cd github-actions
+          #cd github-actions
+          ls -la
           xcodebuild test \
             -workspace github-actions.xcworkspace \
             -scheme "github-actions" \
