E

diff --git a/.github/workflows/use reusable.yml b/.github/workflows/use reusable.yml
--- a/.github/workflows/use reusable.yml
+++ b/.github/workflows/use reusable.yml
@@ -13,13 +13,20 @@ jobs:
           uses: actions/checkout@v3
 
         - name: List directory contents
-          run: ls
+          run: ls -la
 
         - name: Archive artifact
           uses: actions/upload-artifact@v3
           with:
             name: ios-info-files
             path: ./github-actions/github-actions/Resources/configuration.json
+
+        - name: Check if artifact exists
+          run: |
+                if [ ! -f ./github-actions/github-actions/Resources/configuration.json ]; then
+                  echo "Artifact not found!"
+                  exit 1
+                fi
 
     deploy:
         needs: start
